### ISSUE TITLE
Upgrade?

### ISSUE THREAD

**Issue by brj** [douglarek/ricard#1]
Hi @douglarek       
I'm no longer maintaining omf, and would appreciate a ton if you can upgrade to [fisherman](https://github.com/fisherman/fisherman):

* Why? fisherman/fisherman#69 (comment)

Everything, including legacy plugins/themes work great with fisherman, but new content is no longer compat. with oh-my-fish.

If you need help with anything, I'm just a ping away :)

**Comment by douglarek** [comment]
@brj ok, any way thanks

**Comment by brj** [comment]
Thanks!

**Comment by douglarek** [comment]
1fc4111

**Comment by bucaran** [comment]
Closing.
